// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Proposta comercial documents */
interface BusinessProposalDocumentData {
    /**
     * Nome do cliente field in *Proposta comercial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.name
     * - **Tab**: Geral
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * E-mail field in *Proposta comercial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.email
     * - **Tab**: Geral
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Telefone field in *Proposta comercial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 55999999999
     * - **API ID Path**: businessProposal.phoneNumber
     * - **Tab**: Geral
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phoneNumber: prismicT.KeyTextField;
    /**
     * Status field in *Proposta comercial*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.status
     * - **Tab**: Geral
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    status: prismicT.SelectField<"Aguardando aprovação" | "Pagamento homologado" | "Emitindo vouchers">;
    /**
     * locations field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.locations[]
     * - **Tab**: Destino
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    locations: prismicT.GroupField<Simplify<BusinessProposalDocumentDataLocationsItem>>;
    /**
     * Slice Zone field in *Proposta comercial*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.sections[]
     * - **Tab**: Destino
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    sections: prismicT.SliceZone<BusinessProposalDocumentDataSectionsSlice>;
    /**
     * Ordens field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.ordens[]
     * - **Tab**: Pagamentos
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    ordens: prismicT.GroupField<Simplify<BusinessProposalDocumentDataOrdensItem>>;
    /**
     * accommodations field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.accommodations[]
     * - **Tab**: Hospedagens
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    accommodations: prismicT.GroupField<Simplify<BusinessProposalDocumentDataAccommodationsItem>>;
    /**
     * Translados field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[]
     * - **Tab**: Translados
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    transfers: prismicT.GroupField<Simplify<BusinessProposalDocumentDataTransfersItem>>;
    /**
     * Itinerário field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.itinerary[]
     * - **Tab**: Roteiro
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    itinerary: prismicT.GroupField<Simplify<BusinessProposalDocumentDataItineraryItem>>;
    /**
     * Serviços field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.services[]
     * - **Tab**: Serviços
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    services: prismicT.GroupField<Simplify<BusinessProposalDocumentDataServicesItem>>;
    /**
     * Observações field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.remarks[]
     * - **Tab**: Observações
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    remarks: prismicT.GroupField<Simplify<BusinessProposalDocumentDataRemarksItem>>;
    /**
     * Clientes field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.travelers[]
     * - **Tab**: Viajantes
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    travelers: prismicT.GroupField<Simplify<BusinessProposalDocumentDataTravelersItem>>;
}
/**
 * Item in Proposta comercial → locations
 *
 */
export interface BusinessProposalDocumentDataLocationsItem {
    /**
     * Nome field in *Proposta comercial → locations*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.locations[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Chegada field in *Proposta comercial → locations*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.locations[].startAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    startAt: prismicT.TimestampField;
    /**
     * Saída field in *Proposta comercial → locations*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.locations[].endsAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    endsAt: prismicT.TimestampField;
    /**
     * Endereço field in *Proposta comercial → locations*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.locations[].address
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address: prismicT.KeyTextField;
    /**
     * Imagem principal field in *Proposta comercial → locations*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.locations[].cover
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
}
/**
 * Slice for *Proposta comercial → Slice Zone*
 *
 */
type BusinessProposalDocumentDataSectionsSlice = never;
/**
 * Item in Proposta comercial → Ordens
 *
 */
export interface BusinessProposalDocumentDataOrdensItem {
    /**
     * number field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.ordens[].number
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    number: prismicT.KeyTextField;
    /**
     * Desconto field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.ordens[].discount
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    discount: prismicT.NumberField;
    /**
     * Preço total field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.ordens[].price
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    price: prismicT.NumberField;
    /**
     * Link de pagamento field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.ordens[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismicT.KeyTextField;
}
/**
 * Item in Proposta comercial → accommodations
 *
 */
export interface BusinessProposalDocumentDataAccommodationsItem {
    /**
     * Nome field in *Proposta comercial → accommodations*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.accommodations[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Chegada field in *Proposta comercial → accommodations*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.accommodations[].startAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    startAt: prismicT.TimestampField;
    /**
     * Saída field in *Proposta comercial → accommodations*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.accommodations[].endsAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    endsAt: prismicT.DateField;
    /**
     * Descrição field in *Proposta comercial → accommodations*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.accommodations[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Imagem principal field in *Proposta comercial → accommodations*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.accommodations[].cover
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
}
/**
 * Item in Proposta comercial → Translados
 *
 */
export interface BusinessProposalDocumentDataTransfersItem {
    /**
     * Tipo field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[].type
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
    /**
     * Saída field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[].startAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    startAt: prismicT.TimestampField;
    /**
     * Chegada field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[].endsAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    endsAt: prismicT.TimestampField;
    /**
     * Localização inicial field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[].startingLocation
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    startingLocation: prismicT.KeyTextField;
    /**
     * Localização final field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[].finalLocation
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    finalLocation: prismicT.KeyTextField;
    /**
     * Descrição field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.transfers[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Itinerário
 *
 */
export interface BusinessProposalDocumentDataItineraryItem {
    /**
     * Dia field in *Proposta comercial → Itinerário*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.itinerary[].day
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    day: prismicT.TimestampField;
    /**
     * Descrição field in *Proposta comercial → Itinerário*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.itinerary[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Serviços
 *
 */
export interface BusinessProposalDocumentDataServicesItem {
    /**
     * Nome field in *Proposta comercial → Serviços*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.services[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Descrição field in *Proposta comercial → Serviços*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.services[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Observações
 *
 */
export interface BusinessProposalDocumentDataRemarksItem {
    /**
     * Comentário field in *Proposta comercial → Observações*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.remarks[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Clientes
 *
 */
export interface BusinessProposalDocumentDataTravelersItem {
    /**
     * Nome field in *Proposta comercial → Clientes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.travelers[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * E-mail field in *Proposta comercial → Clientes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.travelers[].email
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Telefone field in *Proposta comercial → Clientes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: businessProposal.travelers[].phone
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone: prismicT.KeyTextField;
}
/**
 * Proposta comercial document from Prismic
 *
 * - **API ID**: `businessProposal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BusinessProposalDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<BusinessProposalDocumentData>, "businessProposal", Lang>;
/** Content for Pages documents */
interface PagesDocumentData {
    /**
     * title field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.title
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.description
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Thumbnail field in *Pages*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.image
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"square">;
    /**
     * canonical field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.canonical
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    canonical: prismicT.KeyTextField;
    /**
     * nofollow field in *Pages*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: pages.nofollow
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    nofollow: prismicT.BooleanField;
    /**
     * noIndex field in *Pages*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: pages.noindex
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    noindex: prismicT.BooleanField;
    /**
     * Keywords field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: viagem, turismo
     * - **API ID Path**: pages.keywords
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Pages*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.slices[]
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PagesDocumentDataSlicesSlice>;
    /**
     * JSON field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: { "children": [] }
     * - **API ID Path**: pages.data
     * - **Tab**: JSON
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    data: prismicT.KeyTextField;
}
/**
 * Slice for *Pages → Slice Zone*
 *
 */
type PagesDocumentDataSlicesSlice = FreeJsonSlice | SectionBaseSlice;
/**
 * Pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PagesDocumentData>, "pages", Lang>;
/** Content for Site Template documents */
interface SiteTemplateDocumentData {
    /**
     * title field in *Site Template*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.title
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Site Template*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.description
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Thumbnail field in *Site Template*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.image
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"square">;
    /**
     * Keywords field in *Site Template*
     *
     * - **Field Type**: Text
     * - **Placeholder**: viagem, turismo
     * - **API ID Path**: siteTemplate.keywords
     * - **Tab**: Seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismicT.KeyTextField;
    /**
     * Menu field in *Site Template*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.menu[]
     * - **Tab**: Navbar
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menu: prismicT.GroupField<Simplify<SiteTemplateDocumentDataMenuItem>>;
    /**
     * Slogan field in *Site Template*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.slogan
     * - **Tab**: Footer
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    slogan: prismicT.KeyTextField;
    /**
     * Social field in *Site Template*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.social[]
     * - **Tab**: Footer
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social: prismicT.GroupField<Simplify<SiteTemplateDocumentDataSocialItem>>;
    /**
     * sitemap field in *Site Template*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.sitemap[]
     * - **Tab**: Footer
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    sitemap: prismicT.GroupField<Simplify<SiteTemplateDocumentDataSitemapItem>>;
}
/**
 * Item in Site Template → Menu
 *
 */
export interface SiteTemplateDocumentDataMenuItem {
    /**
     * Texto field in *Site Template → Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.menu[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Link field in *Site Template → Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.menu[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismicT.KeyTextField;
    /**
     * Destaque field in *Site Template → Menu*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: siteTemplate.menu[].highlight
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    highlight: prismicT.BooleanField;
}
/**
 * Item in Site Template → Social
 *
 */
export interface SiteTemplateDocumentDataSocialItem {
    /**
     * Nome do ícone field in *Site Template → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.social[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    icon: prismicT.KeyTextField;
    /**
     * Link field in *Site Template → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.social[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismicT.KeyTextField;
    /**
     * Rede social field in *Site Template → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Facebook
     * - **API ID Path**: siteTemplate.social[].alt
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    alt: prismicT.KeyTextField;
}
/**
 * Item in Site Template → sitemap
 *
 */
export interface SiteTemplateDocumentDataSitemapItem {
    /**
     * Agrupar pelo nome field in *Site Template → sitemap*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Fale Conosco
     * - **API ID Path**: siteTemplate.sitemap[].group
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    group: prismicT.KeyTextField;
    /**
     * Text field in *Site Template → sitemap*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.sitemap[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Link field in *Site Template → sitemap*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: siteTemplate.sitemap[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismicT.KeyTextField;
    /**
     * Abrir em nova aba? field in *Site Template → sitemap*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: siteTemplate.sitemap[].isExternal
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    isExternal: prismicT.BooleanField;
}
/**
 * Site Template document from Prismic
 *
 * - **API ID**: `siteTemplate`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteTemplateDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SiteTemplateDocumentData>, "siteTemplate", Lang>;
export type AllDocumentTypes = BusinessProposalDocument | PagesDocument | SiteTemplateDocument;
/**
 * Primary content in FreeJson → Primary
 *
 */
interface FreeJsonSliceCustomComponentPrimary {
    /**
     * id field in *FreeJson → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: freeJson.primary.id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    id: prismicT.KeyTextField;
    /**
     * component field in *FreeJson → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: freeJson.primary.component
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    component: prismicT.KeyTextField;
    /**
     * Customizações (JSON) field in *FreeJson → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: { "backgroundColor": "red" }
     * - **API ID Path**: freeJson.primary.data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    data: prismicT.KeyTextField;
}
/**
 * Item in FreeJson → Items
 *
 */
export interface FreeJsonSliceCustomComponentItem {
    /**
     * Conteúdo JSON (children) field in *FreeJson → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: { "title": "Meu título" }
     * - **API ID Path**: freeJson.items[].children
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    children: prismicT.KeyTextField;
}
/**
 * CustomComponent variation for FreeJson Slice
 *
 * - **API ID**: `customComponent`
 * - **Description**: `FreeJson`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FreeJsonSliceCustomComponent = prismicT.SharedSliceVariation<"customComponent", Simplify<FreeJsonSliceCustomComponentPrimary>, Simplify<FreeJsonSliceCustomComponentItem>>;
/**
 * Slice variation for *FreeJson*
 *
 */
type FreeJsonSliceVariation = FreeJsonSliceCustomComponent;
/**
 * FreeJson Shared Slice
 *
 * - **API ID**: `freeJson`
 * - **Description**: `FreeJson`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FreeJsonSlice = prismicT.SharedSlice<"freeJson", FreeJsonSliceVariation>;
/**
 * Primary content in SectionBase → Primary
 *
 */
interface SectionBaseSliceDefaultPrimary {
    /**
     * id field in *SectionBase → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sectionBase.primary.id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    id: prismicT.KeyTextField;
    /**
     * container field in *SectionBase → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Tamanho do container da seção
     * - **API ID Path**: sectionBase.primary.container
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    container: prismicT.SelectField<"none" | "sm" | "md" | "lg" | "full">;
    /**
     * Customizações (JSON) field in *SectionBase → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: { "backgroundColor": "red" }
     * - **API ID Path**: sectionBase.primary.data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    data: prismicT.KeyTextField;
}
/**
 * Item in SectionBase → Items
 *
 */
export interface SectionBaseSliceDefaultItem {
    /**
     * Conteúdo JSON (children) field in *SectionBase → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: { "title": "Meu título" }
     * - **API ID Path**: sectionBase.items[].children
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    children: prismicT.KeyTextField;
}
/**
 * Default variation for SectionBase Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SectionBase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SectionBaseSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SectionBaseSliceDefaultPrimary>, Simplify<SectionBaseSliceDefaultItem>>;
/**
 * Slice variation for *SectionBase*
 *
 */
type SectionBaseSliceVariation = SectionBaseSliceDefault;
/**
 * SectionBase Shared Slice
 *
 * - **API ID**: `sectionBase`
 * - **Description**: `SectionBase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SectionBaseSlice = prismicT.SharedSlice<"sectionBase", SectionBaseSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BusinessProposalDocumentData, BusinessProposalDocumentDataLocationsItem, BusinessProposalDocumentDataSectionsSlice, BusinessProposalDocumentDataOrdensItem, BusinessProposalDocumentDataAccommodationsItem, BusinessProposalDocumentDataTransfersItem, BusinessProposalDocumentDataItineraryItem, BusinessProposalDocumentDataServicesItem, BusinessProposalDocumentDataRemarksItem, BusinessProposalDocumentDataTravelersItem, BusinessProposalDocument, PagesDocumentData, PagesDocumentDataSlicesSlice, PagesDocument, SiteTemplateDocumentData, SiteTemplateDocumentDataMenuItem, SiteTemplateDocumentDataSocialItem, SiteTemplateDocumentDataSitemapItem, SiteTemplateDocument, AllDocumentTypes, FreeJsonSliceCustomComponentPrimary, FreeJsonSliceCustomComponentItem, FreeJsonSliceCustomComponent, FreeJsonSliceVariation, FreeJsonSlice, SectionBaseSliceDefaultPrimary, SectionBaseSliceDefaultItem, SectionBaseSliceDefault, SectionBaseSliceVariation, SectionBaseSlice };
    }
}
