// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Proposta comercial documents */
interface BusinessProposalDocumentData {
    /**
     * Nome do cliente field in *Proposta comercial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.name
     * - **Tab**: Cliente
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * E-mail field in *Proposta comercial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.email
     * - **Tab**: Cliente
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Telefone field in *Proposta comercial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 55999999999
     * - **API ID Path**: business_proposal.phoneNumber
     * - **Tab**: Cliente
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phoneNumber: prismicT.KeyTextField;
    /**
     * locations field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.locations[]
     * - **Tab**: Destino
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    locations: prismicT.GroupField<Simplify<BusinessProposalDocumentDataLocationsItem>>;
    /**
     * Slice Zone field in *Proposta comercial*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.slices1[]
     * - **Tab**: Destino
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices1: prismicT.SliceZone<BusinessProposalDocumentDataSlices1Slice>;
    /**
     * Ordens field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.ordens[]
     * - **Tab**: Pagamento
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    ordens: prismicT.GroupField<Simplify<BusinessProposalDocumentDataOrdensItem>>;
    /**
     * acommodations field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.acommodations[]
     * - **Tab**: Hospedagens
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    acommodations: prismicT.GroupField<Simplify<BusinessProposalDocumentDataAcommodationsItem>>;
    /**
     * Translados field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[]
     * - **Tab**: Translados
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    transfers: prismicT.GroupField<Simplify<BusinessProposalDocumentDataTransfersItem>>;
    /**
     * Itinerário field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.itinerary[]
     * - **Tab**: Roteiro
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    itinerary: prismicT.GroupField<Simplify<BusinessProposalDocumentDataItineraryItem>>;
    /**
     * Serviços field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.services[]
     * - **Tab**: Serviços
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    services: prismicT.GroupField<Simplify<BusinessProposalDocumentDataServicesItem>>;
    /**
     * Observações field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.remarks[]
     * - **Tab**: Observações
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    remarks: prismicT.GroupField<Simplify<BusinessProposalDocumentDataRemarksItem>>;
    /**
     * Viajantes field in *Proposta comercial*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.travelers[]
     * - **Tab**: Viajantes
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    travelers: prismicT.GroupField<Simplify<BusinessProposalDocumentDataTravelersItem>>;
}
/**
 * Item in Proposta comercial → locations
 *
 */
export interface BusinessProposalDocumentDataLocationsItem {
    /**
     * Nome field in *Proposta comercial → locations*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.locations[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Chegada field in *Proposta comercial → locations*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.locations[].startAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    startAt: prismicT.DateField;
    /**
     * Saída field in *Proposta comercial → locations*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.locations[].endsAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    endsAt: prismicT.DateField;
    /**
     * Endereço field in *Proposta comercial → locations*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.locations[].address
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address: prismicT.KeyTextField;
    /**
     * Imagem principal field in *Proposta comercial → locations*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.locations[].cover
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
}
/**
 * Slice for *Proposta comercial → Slice Zone*
 *
 */
type BusinessProposalDocumentDataSlices1Slice = never;
/**
 * Item in Proposta comercial → Ordens
 *
 */
export interface BusinessProposalDocumentDataOrdensItem {
    /**
     * number field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.ordens[].number
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    number: prismicT.KeyTextField;
    /**
     * Desconto field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.ordens[].discount
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    discount: prismicT.NumberField;
    /**
     * Preço total field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.ordens[].price
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    price: prismicT.NumberField;
    /**
     * Link de pagamento field in *Proposta comercial → Ordens*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.ordens[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismicT.KeyTextField;
}
/**
 * Item in Proposta comercial → acommodations
 *
 */
export interface BusinessProposalDocumentDataAcommodationsItem {
    /**
     * Nome field in *Proposta comercial → acommodations*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.acommodations[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Chegada field in *Proposta comercial → acommodations*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.acommodations[].startAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    startAt: prismicT.TimestampField;
    /**
     * Saída field in *Proposta comercial → acommodations*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.acommodations[].endsAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    endsAt: prismicT.DateField;
    /**
     * Descrição field in *Proposta comercial → acommodations*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.acommodations[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Imagem principal field in *Proposta comercial → acommodations*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.acommodations[].cover
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
}
/**
 * Item in Proposta comercial → Translados
 *
 */
export interface BusinessProposalDocumentDataTransfersItem {
    /**
     * Tipo field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[].type
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
    /**
     * Saída field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[].startAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    startAt: prismicT.TimestampField;
    /**
     * Chegada field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[].endsAt
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    endsAt: prismicT.TimestampField;
    /**
     * Localização inicial field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[].startingLocation
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    startingLocation: prismicT.KeyTextField;
    /**
     * Localização final field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[].finalLocation
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    finalLocation: prismicT.KeyTextField;
    /**
     * Descrição field in *Proposta comercial → Translados*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.transfers[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Itinerário
 *
 */
export interface BusinessProposalDocumentDataItineraryItem {
    /**
     * Dia field in *Proposta comercial → Itinerário*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.itinerary[].day
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    day: prismicT.TimestampField;
    /**
     * Descrição field in *Proposta comercial → Itinerário*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.itinerary[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Serviços
 *
 */
export interface BusinessProposalDocumentDataServicesItem {
    /**
     * Nome field in *Proposta comercial → Serviços*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.services[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Descrição field in *Proposta comercial → Serviços*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.services[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Observações
 *
 */
export interface BusinessProposalDocumentDataRemarksItem {
    /**
     * Comentário field in *Proposta comercial → Observações*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.remarks[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Item in Proposta comercial → Viajantes
 *
 */
export interface BusinessProposalDocumentDataTravelersItem {
    /**
     * Nome field in *Proposta comercial → Viajantes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.travelers[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * E-mail field in *Proposta comercial → Viajantes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.travelers[].email
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Telefone field in *Proposta comercial → Viajantes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_proposal.travelers[].phone
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone: prismicT.KeyTextField;
}
/**
 * Proposta comercial document from Prismic
 *
 * - **API ID**: `business_proposal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BusinessProposalDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<BusinessProposalDocumentData>, "business_proposal", Lang>;
export type AllDocumentTypes = BusinessProposalDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BusinessProposalDocumentData, BusinessProposalDocumentDataLocationsItem, BusinessProposalDocumentDataSlices1Slice, BusinessProposalDocumentDataOrdensItem, BusinessProposalDocumentDataAcommodationsItem, BusinessProposalDocumentDataTransfersItem, BusinessProposalDocumentDataItineraryItem, BusinessProposalDocumentDataServicesItem, BusinessProposalDocumentDataRemarksItem, BusinessProposalDocumentDataTravelersItem, BusinessProposalDocument, AllDocumentTypes };
    }
}
