import { FlightDetails, FlightView } from "@/core/types";

export const mock: FlightDetails[] = [
  {
    id: 1,
    airlineCompanyLogoUrl:
      "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico31.jpg",
    flightTime: "01:55:00",
    departure: "2025-03-01T20:45:00",
    arrival: "2025-03-01T22:40:00",
    classFamily: "adsdasdsa",
    flightCode: "JJ 3603",
    luggageInfo: "Somente bagagem de mão",
    fromAirportCode: "POA",
    fromAirportName: "Salgado Filho",
    fromAirportAddress: "dsadsa",
    fromAirportServedCity: "Porto Alegre",
    fromAirportServedStateProvinceCode: "RS",
    fromAirportServedCountry: "Brasil",
    toAirportCode: "GIG",
    toAirportName: "Rio Galeão / Antônio Carlos Jobim",
    toAirportAddress: "dasdasdsasda",
    toAirportServedCity: "Rio de Janeiro",
    toAirportServedStateProvinceCode: "RJ",
    toAirportServedCountry: "Brasil",
    connections: 0,
  },
  {
    id: 2,
    airlineCompanyLogoUrl:
      "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico31.jpg",
    flightTime: "01:55:00",
    departure: "2025-03-01T20:45:00",
    arrival: "2025-03-01T22:40:00",
    classFamily: "adsdasdsa",
    flightCode: "JJ 3603",
    luggageInfo: "Somente bagagem de mão",
    fromAirportCode: "POA",
    fromAirportName: "Salgado Filho",
    fromAirportAddress: "dsadsa",
    fromAirportServedCity: "Porto Alegre",
    fromAirportServedStateProvinceCode: "RS",
    fromAirportServedCountry: "Brasil",
    toAirportCode: "GIG",
    toAirportName: "Rio Galeão / Antônio Carlos Jobim",
    toAirportAddress: "dasdasdsasda",
    toAirportServedCity: "Rio de Janeiro",
    toAirportServedStateProvinceCode: "RJ",
    toAirportServedCountry: "Brasil",
    connections: 0,
  },
  {
    id: 3,
    airlineCompanyLogoUrl:
      "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico31.jpg",
    flightTime: "01:55:00",
    departure: "2025-03-01T20:45:00",
    arrival: "2025-03-01T22:40:00",
    classFamily: "adsdasdsa",
    flightCode: "JJ 3603",
    luggageInfo: "Somente bagagem de mão",
    fromAirportCode: "POA",
    fromAirportName: "Salgado Filho",
    fromAirportAddress: "dsadsa",
    fromAirportServedCity: "Porto Alegre",
    fromAirportServedStateProvinceCode: "RS",
    fromAirportServedCountry: "Brasil",
    toAirportCode: "GIG",
    toAirportName: "Rio Galeão / Antônio Carlos Jobim",
    toAirportAddress: "dasdasdsasda",
    toAirportServedCity: "Rio de Janeiro",
    toAirportServedStateProvinceCode: "RJ",
    toAirportServedCountry: "Brasil",
    connections: 0,
  },
  {
    id: 4,
    airlineCompanyLogoUrl:
      "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico31.jpg",
    flightTime: "01:55:00",
    departure: "2025-03-01T20:45:00",
    arrival: "2025-03-01T22:40:00",
    classFamily: "adsdasdsa",
    flightCode: "JJ 3603",
    luggageInfo: "Somente bagagem de mão",
    fromAirportCode: "POA",
    fromAirportName: "Salgado Filho",
    fromAirportAddress: "dsadsa",
    fromAirportServedCity: "Porto Alegre",
    fromAirportServedStateProvinceCode: "RS",
    fromAirportServedCountry: "Brasil",
    toAirportCode: "GIG",
    toAirportName: "Rio Galeão / Antônio Carlos Jobim",
    toAirportAddress: "dasdasdsasda",
    toAirportServedCity: "Rio de Janeiro",
    toAirportServedStateProvinceCode: "RJ",
    toAirportServedCountry: "Brasil",
    connections: 0,
  },
  {
    id: 5,
    airlineCompanyLogoUrl:
      "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico31.jpg",
    flightTime: "01:55:00",
    departure: "2025-03-01T20:45:00",
    arrival: "2025-03-01T22:40:00",
    classFamily: "adsdasdsa",
    flightCode: "JJ 3603",
    luggageInfo: "Somente bagagem de mão",
    fromAirportCode: "POA",
    fromAirportName: "Salgado Filho",
    fromAirportAddress: "dsadsa",
    fromAirportServedCity: "Porto Alegre",
    fromAirportServedStateProvinceCode: "RS",
    fromAirportServedCountry: "Brasil",
    toAirportCode: "GIG",
    toAirportName: "Rio Galeão / Antônio Carlos Jobim",
    toAirportAddress: "dasdasdsasda",
    toAirportServedCity: "Rio de Janeiro",
    toAirportServedStateProvinceCode: "RJ",
    toAirportServedCountry: "Brasil",
    connections: 0,
  },
];
