export const mock: any = [
  {
    company: {
      id: 0,
      iataCode: "G3",
      description: "Gol Linhas Aéreas", // companhia aérea
    },
    destination: {
      id: 0,
      iataCode: "FOR",
      description: "FOR - FORTALEZA", // destino
    },
    origin: {
      id: 0,
      iataCode: "POA",
      description: "POA - PORTO ALEGRE", // origem
    },
    supplier: {
      id: 0,
      code: 502,
      name: "Travellink_Flytour",
    },
    subSupplier: {
      id: 0,
      code: 70,
      name: "",
    },
    duration: 755, // duração do voo?,
    id: 10027047,
    externalId:
      "kxUAAB+LCAAAAAAABADtmN2SosgSgF9lw1tnBoofESP2AlDwBwFRQDmxFyWUgAKF/CjtxDzQPsd5sVNoT093z1zMXO3ZiDE6JIvMyqpKPjLT/tyTeiPwoaf0RvSHnnz/VtveqC4b9KG3TqreiKeZuzQLeyNWJKYJ7I16Gtv70Fueiq+m1l2mP5H5NlGPiXaDm1LBIZqFUpEmAQzx3f0mKYhAfI5RVSc5Jkv853PPJJMsUyLTxkRSTZtIFpEYmuE/0txHGmxoenT/6z2W+KoB9DfNl7+If1gmB7jBNUzJ0YYc+2lIXJU4wwHZTPV1L92yL9ZmgUpyr4Qvx4FkDIkNRw4867bEADaE4oH+eKAD9JFj6PCjyMLDRwghQIIIhIPIkJ25+PlAS60kAemRWzq5gN6bwIXV8wCnf+hJHsPqD+m/f5eIrPihJ32LhdStrGjTLizrt9EAzIjlH9GYdirAsHxnprwz40bgOWjTTgU40MnjpoQBJM+hR4PRfaLRZJ1aAN1gjaIM5XWnn5GhCku0eSrQc8wUnPdGB5hWXaDeDL5BIJPAktmyOZckjdEUg7iRlbQLKcGMyLbRPMIzC3COiBjXdVGNKIoMa9SE+FNdwgtK0yQ/fQpw9mlfUpsyKSYXnF5QSOk4whksA1iRGVkB8ziBSYD5T1FyuG85S9Iuxp97Bs46/3oSxXVHVYkOSdsdTZ9pvS/kOORZBzUqE4JjAB9P7wEpeTFmeXjHpbwju2pgXichDDuHXRwtVOElbJMMP5/bye/qJQrJlRgttD825kbSyUIvXt+6ZX/Kyx3tWcf93dNbuphfpeuB1IMuT/4BXQx4edfudDHgLr+ni2FGNP+KLoah+fd00a/oAiz9c3Q9v4W/4frn4WJ/Ga47UXe4NBKE93AxG3rwFi568AO4iJkwYl6nLlpgvktd9zsPuBgaCL/h+pfBxf0qXA+ipG9Nwnu4SF0E9Ju6CH4EF+DfwgX493CxI/AaLpH7Dde/DC7+V+F6EHWHS15/VxZJowmEEXjTdD3apTdwETPmW6f6KIs0/Q4uZsS9brpo8S1c7u+m6/+ersGv0vVA6k7X8y+dd3T9TNPVmbEj7g1dLPc9XfQrutjhz9H1O3X9U3ARKSWbvW/UhWnnpHeVV5Ik93VFenxkaVxnBmi4Y+S0oJ8Oa06pfdq6TpE8PrUMDDJvb4VJbYfN7hznpzZKV97cEbcY7VW+Ohbs9RQq7mpeoPEqsXfUhdtTlxM1S0K3v4rtY4GP8rHB8ymfe1d7QZnGYKGoujwud4zFLb1FM/YH6xkHM7U5R32K8swhJTHShl1Or4OBrAZCJR3deT0sNT1uRW5wsjVL9XRPslBsQ0EuYkDPuWLtR1jrN4F7g+phaaGIb8HuRJ2OnqTuVNXMkz7dzJOpdpu2thGcm5gc8UlsKLwUbw1ax4v8pAzZRbgL+tp1Nw+K9VlRbE/oo7il13YwUQDH5t7FSvv6VLGfLnioxLfZdG3T+fZpGPMJz8pD/gYEjQd75whzh098thnm6QwzatXC9SX2RWe6GwtwxbfxOKZp6amRx44ybvzA4Ja+ynriOhtEA5lO+H7atqJlmTjR/eY6831/06LBbZ/oTlBu9o3pZleeqdjtalMF7Fm47fjj7RgYu9V82dIH45w2QmyE3ix2F+V8XVPVwD1et1yIAG02SjIDblwn6znnmM7AiJZRsJbFmXWNzqJNWQfLExdFfzk9yZkxacFqPWGuc2a8XGW0ivqXducaajsTnXklDxdBDa4ef/GDYoubJN3Ke53XqouT5Rdz3w/PvrtAttBysX8Gx1Y4ua2WpIogMp64vBimD+fjPoeRu8Cqz+rAaUp8BkkDNCE6N3ZeBNFt62QBRs3ATMVb5dt7rh9aR2ggoImnJ6sZN0phqdPNJnUut5UnrpTBaRP5u4mWzNHcsVTFGBe+oM5BfV0N+0jzB94SrZ/O8QoljhUOF8BwW0q73PQNStqk4SxrKiowiEVu2daZbqRenSZF8eTrFH1ls+PtIBd96mBJRiiVS3bJUkniZgBEOb8uzWCgHJWTtiifbFc/7arqdLxFDFUyvlOJEbTNscLmcDg2Cq2qKBnrKJ546qpy1bxvsZWmnC7gkJDrJDPZCirODgUzhT639HCnTBlV1qdXpF68Q8t7iy23WvSPquPNQ3vnSld3cjOmXrpeOVZlnHNJONZOpDYHGplTGQmbE4fUM8wwnh/pEtjBeZOk18uZd80nxrF81VVXGM0Ooc9XC2Yys1kjVk4HhGeTwUZpFvR5L+1M6CdQ7ReNOm/XeCsu3RWnAtXGnoI1BZhhKl9FZS7aMZ4m/WJGLySFNY+xoO5rPJYbx9H8w/bpel0uM9WhttHQcZPrcOjp0Xbnau1OV/AWnOlqfMx3i2moazu20seV83S7Tuy9x42vVRn19S3XLHJ2cUUTkSuFWsBbhKCJIk5q62UlC/l2sQHDqrypDb1e4OWyQrqtTjAFhfYyyShqJUO5Fox7bpT+/LP7LyOMum48JLUtOZAM3JXADz0bHVCJ8iCBFmyfq1J+6FJ9+lzbuuz9NdUChuF5Rhy8uHMTGKFsFv6yJ4F+8aHiMkcBIhVBwWES/eSu/vryPwtkgQaTFQAA",
    numSteps: 4, // quantas paradas tem a viagem
    segment: "",
    durationTime: "12:35:00", // duração total da viagem
    totalPrice: 2137.77, // Preço total do voo
    totalPriceOnlyFlights: 1843.8,
    totalNetPriceOnlyFlights: 1843.8,
    totalTax: 293.97,
    totalFee: 184.38,
    totalBoardingFee: 109.59,
    pricePerAdult: 1843.8,
    pricePerChild: null,
    pricePerBaby: null,
    flights: [
      {
        number: "1715", // número da aeronave
        id: 0,
        cabin: "Econômica", // classe do Voo
        isLuggageIncluded: false, // se há bagagem incluida ou n
        luggageIndicator: 2, // Número máximo de bagagens
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3", //Identificador da companhia aérea
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: false,
        arrivalDate: "2025-04-01T14:10:00", // data de chegada
        arrivalTime: "14:10:00", // horário de chegada
        departureDate: "2025-04-01T12:35:00", //data de saída
        departureTime: "12:35:00", //horário de saída
        duration: "01:35:00", // duração do voo
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "CGH", //Abreviação da cidade
          description: "CGH - SAO PAULO", //lugar de chegada
        },
        origin: {
          id: 0,
          iataCode: "POA", //Abreviação da cidade
          description: "POA - PORTO ALEGRE", // lugar de partida
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "1130",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-01T22:05:00",
        arrivalTime: "22:05:00",
        departureDate: "2025-04-01T21:00:00",
        departureTime: "21:00:00",
        duration: "01:05:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "CWB",
          description: "CWB - CURITIBA",
        },
        origin: {
          id: 0,
          iataCode: "CGH",
          description: "CGH - SAO PAULO",
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "2017",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-02T07:20:00",
        arrivalTime: "07:20:00",
        departureDate: "2025-04-02T06:00:00",
        departureTime: "06:00:00",
        duration: "01:20:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "GIG",
          description: "GIG - RIO DE JANEIRO",
        },
        origin: {
          id: 0,
          iataCode: "CWB",
          description: "CWB - CURITIBA",
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "2094",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-02T15:20:00",
        arrivalTime: "15:20:00",
        departureDate: "2025-04-02T12:10:00",
        departureTime: "12:10:00",
        duration: "03:10:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "FOR",
          description: "FOR - FORTALEZA",
        },
        origin: {
          id: 0,
          iataCode: "GIG",
          description: "GIG - RIO DE JANEIRO",
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "1709",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: false,
        arrivalDate: "2025-04-10T20:00:00",
        arrivalTime: "20:00:00",
        departureDate: "2025-04-10T17:15:00",
        departureTime: "17:15:00",
        duration: "02:45:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "BSB",
          description: "BSB - BRASILIA",
        },
        origin: {
          id: 0,
          iataCode: "FOR",
          description: "FOR - FORTALEZA",
        },
        numberOfStops: 0,
        segment: "V",
      },
      {
        number: "1738",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-10T23:40:00",
        arrivalTime: "23:40:00",
        departureDate: "2025-04-10T21:00:00",
        departureTime: "21:00:00",
        duration: "02:40:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "POA",
          description: "POA - PORTO ALEGRE",
        },
        origin: {
          id: 0,
          iataCode: "BSB",
          description: "BSB - BRASILIA",
        },
        numberOfStops: 0,
        segment: "V",
      },
    ],
  },
  {
    company: {
      id: 0,
      iataCode: "G3",
      description: "Gol Linhas Aéreas", // companhia aérea
    },
    destination: {
      id: 0,
      iataCode: "FOR",
      description: "FOR - FORTALEZA", // destino
    },
    origin: {
      id: 0,
      iataCode: "POA",
      description: "POA - PORTO ALEGRE", // origem
    },
    supplier: {
      id: 0,
      code: 502,
      name: "Travellink_Flytour",
    },
    subSupplier: {
      id: 0,
      code: 70,
      name: "",
    },
    duration: 755, // duração do voo?,
    id: 10027047,
    externalId:
      "kxUAAB+LCAAAAAAABADtmN2SosgSgF9lw1tnBoofESP2AlDwBwFRQDmxFyWUgAKF/CjtxDzQPsd5sVNoT093z1zMXO3ZiDE6JIvMyqpKPjLT/tyTeiPwoaf0RvSHnnz/VtveqC4b9KG3TqreiKeZuzQLeyNWJKYJ7I16Gtv70Fueiq+m1l2mP5H5NlGPiXaDm1LBIZqFUpEmAQzx3f0mKYhAfI5RVSc5Jkv853PPJJMsUyLTxkRSTZtIFpEYmuE/0txHGmxoenT/6z2W+KoB9DfNl7+If1gmB7jBNUzJ0YYc+2lIXJU4wwHZTPV1L92yL9ZmgUpyr4Qvx4FkDIkNRw4867bEADaE4oH+eKAD9JFj6PCjyMLDRwghQIIIhIPIkJ25+PlAS60kAemRWzq5gN6bwIXV8wCnf+hJHsPqD+m/f5eIrPihJ32LhdStrGjTLizrt9EAzIjlH9GYdirAsHxnprwz40bgOWjTTgU40MnjpoQBJM+hR4PRfaLRZJ1aAN1gjaIM5XWnn5GhCku0eSrQc8wUnPdGB5hWXaDeDL5BIJPAktmyOZckjdEUg7iRlbQLKcGMyLbRPMIzC3COiBjXdVGNKIoMa9SE+FNdwgtK0yQ/fQpw9mlfUpsyKSYXnF5QSOk4whksA1iRGVkB8ziBSYD5T1FyuG85S9Iuxp97Bs46/3oSxXVHVYkOSdsdTZ9pvS/kOORZBzUqE4JjAB9P7wEpeTFmeXjHpbwju2pgXichDDuHXRwtVOElbJMMP5/bye/qJQrJlRgttD825kbSyUIvXt+6ZX/Kyx3tWcf93dNbuphfpeuB1IMuT/4BXQx4edfudDHgLr+ni2FGNP+KLoah+fd00a/oAiz9c3Q9v4W/4frn4WJ/Ga47UXe4NBKE93AxG3rwFi568AO4iJkwYl6nLlpgvktd9zsPuBgaCL/h+pfBxf0qXA+ipG9Nwnu4SF0E9Ju6CH4EF+DfwgX493CxI/AaLpH7Dde/DC7+V+F6EHWHS15/VxZJowmEEXjTdD3apTdwETPmW6f6KIs0/Q4uZsS9brpo8S1c7u+m6/+ersGv0vVA6k7X8y+dd3T9TNPVmbEj7g1dLPc9XfQrutjhz9H1O3X9U3ARKSWbvW/UhWnnpHeVV5Ik93VFenxkaVxnBmi4Y+S0oJ8Oa06pfdq6TpE8PrUMDDJvb4VJbYfN7hznpzZKV97cEbcY7VW+Ohbs9RQq7mpeoPEqsXfUhdtTlxM1S0K3v4rtY4GP8rHB8ymfe1d7QZnGYKGoujwud4zFLb1FM/YH6xkHM7U5R32K8swhJTHShl1Or4OBrAZCJR3deT0sNT1uRW5wsjVL9XRPslBsQ0EuYkDPuWLtR1jrN4F7g+phaaGIb8HuRJ2OnqTuVNXMkz7dzJOpdpu2thGcm5gc8UlsKLwUbw1ax4v8pAzZRbgL+tp1Nw+K9VlRbE/oo7il13YwUQDH5t7FSvv6VLGfLnioxLfZdG3T+fZpGPMJz8pD/gYEjQd75whzh098thnm6QwzatXC9SX2RWe6GwtwxbfxOKZp6amRx44ybvzA4Ja+ynriOhtEA5lO+H7atqJlmTjR/eY6831/06LBbZ/oTlBu9o3pZleeqdjtalMF7Fm47fjj7RgYu9V82dIH45w2QmyE3ix2F+V8XVPVwD1et1yIAG02SjIDblwn6znnmM7AiJZRsJbFmXWNzqJNWQfLExdFfzk9yZkxacFqPWGuc2a8XGW0ivqXducaajsTnXklDxdBDa4ef/GDYoubJN3Ke53XqouT5Rdz3w/PvrtAttBysX8Gx1Y4ua2WpIogMp64vBimD+fjPoeRu8Cqz+rAaUp8BkkDNCE6N3ZeBNFt62QBRs3ATMVb5dt7rh9aR2ggoImnJ6sZN0phqdPNJnUut5UnrpTBaRP5u4mWzNHcsVTFGBe+oM5BfV0N+0jzB94SrZ/O8QoljhUOF8BwW0q73PQNStqk4SxrKiowiEVu2daZbqRenSZF8eTrFH1ls+PtIBd96mBJRiiVS3bJUkniZgBEOb8uzWCgHJWTtiifbFc/7arqdLxFDFUyvlOJEbTNscLmcDg2Cq2qKBnrKJ546qpy1bxvsZWmnC7gkJDrJDPZCirODgUzhT639HCnTBlV1qdXpF68Q8t7iy23WvSPquPNQ3vnSld3cjOmXrpeOVZlnHNJONZOpDYHGplTGQmbE4fUM8wwnh/pEtjBeZOk18uZd80nxrF81VVXGM0Ooc9XC2Yys1kjVk4HhGeTwUZpFvR5L+1M6CdQ7ReNOm/XeCsu3RWnAtXGnoI1BZhhKl9FZS7aMZ4m/WJGLySFNY+xoO5rPJYbx9H8w/bpel0uM9WhttHQcZPrcOjp0Xbnau1OV/AWnOlqfMx3i2moazu20seV83S7Tuy9x42vVRn19S3XLHJ2cUUTkSuFWsBbhKCJIk5q62UlC/l2sQHDqrypDb1e4OWyQrqtTjAFhfYyyShqJUO5Fox7bpT+/LP7LyOMum48JLUtOZAM3JXADz0bHVCJ8iCBFmyfq1J+6FJ9+lzbuuz9NdUChuF5Rhy8uHMTGKFsFv6yJ4F+8aHiMkcBIhVBwWES/eSu/vryPwtkgQaTFQAA",
    numSteps: 4, // quantas paradas tem a viagem
    segment: "",
    durationTime: "12:35:00", // duração total da viagem
    totalPrice: 2137.77, // Preço total do voo
    totalPriceOnlyFlights: 1843.8,
    totalNetPriceOnlyFlights: 1843.8,
    totalTax: 293.97,
    totalFee: 184.38,
    totalBoardingFee: 109.59,
    pricePerAdult: 1843.8,
    pricePerChild: null,
    pricePerBaby: null,
    flights: [
      {
        number: "1715", // número da aeronave
        id: 0,
        cabin: "Econômica", // classe do Voo
        isLuggageIncluded: false, // se há bagagem incluida ou n
        luggageIndicator: 2, // Número máximo de bagagens
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3", //Identificador da companhia aérea
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: false,
        arrivalDate: "2025-04-01T14:10:00", // data de chegada
        arrivalTime: "14:10:00", // horário de chegada
        departureDate: "2025-04-01T12:35:00", //data de saída
        departureTime: "12:35:00", //horário de saída
        duration: "01:35:00", // duração do voo
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "CGH", //Abreviação da cidade
          description: "CGH - SAO PAULO", //lugar de chegada
        },
        origin: {
          id: 0,
          iataCode: "POA", //Abreviação da cidade
          description: "POA - PORTO ALEGRE", // lugar de partida
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "1130",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-01T22:05:00",
        arrivalTime: "22:05:00",
        departureDate: "2025-04-01T21:00:00",
        departureTime: "21:00:00",
        duration: "01:05:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "CWB",
          description: "CWB - CURITIBA",
        },
        origin: {
          id: 0,
          iataCode: "CGH",
          description: "CGH - SAO PAULO",
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "2017",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-02T07:20:00",
        arrivalTime: "07:20:00",
        departureDate: "2025-04-02T06:00:00",
        departureTime: "06:00:00",
        duration: "01:20:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "GIG",
          description: "GIG - RIO DE JANEIRO",
        },
        origin: {
          id: 0,
          iataCode: "CWB",
          description: "CWB - CURITIBA",
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "2094",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-02T15:20:00",
        arrivalTime: "15:20:00",
        departureDate: "2025-04-02T12:10:00",
        departureTime: "12:10:00",
        duration: "03:10:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "FOR",
          description: "FOR - FORTALEZA",
        },
        origin: {
          id: 0,
          iataCode: "GIG",
          description: "GIG - RIO DE JANEIRO",
        },
        numberOfStops: 0,
        segment: "I",
      },
      {
        number: "1709",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: false,
        arrivalDate: "2025-04-10T20:00:00",
        arrivalTime: "20:00:00",
        departureDate: "2025-04-10T17:15:00",
        departureTime: "17:15:00",
        duration: "02:45:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "BSB",
          description: "BSB - BRASILIA",
        },
        origin: {
          id: 0,
          iataCode: "FOR",
          description: "FOR - FORTALEZA",
        },
        numberOfStops: 0,
        segment: "V",
      },
      {
        number: "1738",
        id: 0,
        cabin: "Econômica",
        isLuggageIncluded: false,
        luggageIndicator: 2,
        luggageWeight: 0,
        luggageCount: 0,
        luggageMeasureUnit: "KG TOTAL",
        mandatoryAirline: {
          id: 0,
          iataCode: "G3",
          description: "Gol Linhas Aéreas",
        },
        operationAirline: {
          id: 0,
          iataCode: "",
          description: "",
        },
        class: "B",
        company: null,
        isConnection: true,
        arrivalDate: "2025-04-10T23:40:00",
        arrivalTime: "23:40:00",
        departureDate: "2025-04-10T21:00:00",
        departureTime: "21:00:00",
        duration: "02:40:00",
        equipment: "738",
        stopovers: null,
        family: "Light",
        familyCode: "LIG",
        segmentGroup: 0,
        iconUrl: "https://conteudo.travellink.com.br/TripEvolved/Logomarcas/companhiaico5.gif",
        companyLocatorId: null,
        destination: {
          id: 0,
          iataCode: "POA",
          description: "POA - PORTO ALEGRE",
        },
        origin: {
          id: 0,
          iataCode: "BSB",
          description: "BSB - BRASILIA",
        },
        numberOfStops: 0,
        segment: "V",
      },
    ],
  },
];
