// Code generated by Slice Machine. DO NOT EDIT.

import FreeJson from './FreeJson';
import SectionBase from './SectionBase';

export {
	FreeJson,
	SectionBase,
};

export const components = {
	freeJson: FreeJson,
	section_base: SectionBase,
};
