import { NextUIProvider } from "@nextui-org/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import { fontFamilyClassName } from "../configs/font-family.config";
import { lightTheme } from "../configs/theme.config";

import "@/styles/colors.css";
import "@/styles/globals.css";

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Trip Evolved</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextUIProvider theme={lightTheme}>
        <div className={fontFamilyClassName}>
          <Component {...pageProps} />
        </div>
      </NextUIProvider>
    </>
  );
};

export default App;
